services:
  default-build-env:
    image: default-build-env
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
    container_name: default-build-env
    restart: unless-stopped
    ports:
      - "30080:8080"
      - "30022:22"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - default-build-env

networks:
  default-build-env:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.35.0/24