name: Build Multi-Arch Docker Images

on:
  push:
    branches: [ "main", "master" ]
    tags: [ 'v*' ]
  # 定时任务：每天 UTC 0:30 (北京时间 8:30) 执行
  schedule:
    - cron: '30 0 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ==========================================
  # Job 1: 优先编译 default 目录
  # ==========================================
  build-default:
    name: Build Base (default)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./default
          file: ./default/Dockerfile
          platforms: linux/amd64,linux/arm64
          # 因为去掉了 PR 触发，这里只要触发就会直接 push
          push: true
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Default programming environment
          tags: ghcr.io/${{ github.repository_owner }}/default:latest,ghcr.io/${{ github.repository_owner }}/default:${{ github.run_id }}

  # ==========================================
  # Job 2: 并行编译其他目录
  # ==========================================
  build-others:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: build-default
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        include:
          - name: "cangjie"        
            tag: "latest"
            description: "Cangjie Programming Environment"
            
          - name: "vite"        
            tag: "latest"
            description: "VitePlus Programming Environment"

      fail-fast: false 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./${{ matrix.name }}
          file: ./${{ matrix.name }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          # 因为去掉了 PR 触发，这里只要触发就会直接 push
          push: true
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=${{ matrix.description }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ matrix.tag }},ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.run_id }}
